import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Spinner } from './ui/spinner';
import {
  ArrowUp,
  FileUp,
  Github,
  GitBranch,
  Hash,
  Pencil,
  Shield,
  ShieldAlert,
  Sparkles,
  Trello,
  X,
} from 'lucide-react';
import { MultiProviderDropdown } from './MultiProviderDropdown';
import { type Provider } from '../types';
import { type ProviderRun } from '../types/chat';
import { Separator } from './ui/separator';
import { providerMeta } from '../providers/meta';
import { isValidProviderId } from '@shared/providers/registry';
import { type LinearIssueSummary } from '../types/linear';
import { type GitHubIssueSummary } from '../types/github';
import {
  generateFriendlyTaskName,
  normalizeTaskName,
  MAX_TASK_NAME_LENGTH,
} from '../lib/taskNames';

const DEFAULT_PROVIDER: Provider = 'claude';
const DEFAULT_BRANCH_TEMPLATE = 'agent/{slug}-{timestamp}';

const slugifyBranchName = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

const sanitizeBranchName = (name: string): string => {
  let next = name
    .replace(/\s+/g, '-')
    .replace(/[^A-Za-z0-9._\/-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/\/+/g, '/');
  next = next.replace(/^[./-]+/, '').replace(/[./-]+$/, '');
  if (!next || next === 'HEAD') {
    next = `agent/${slugifyBranchName('task')}-${Date.now()}`;
  }
  return next;
};

const renderBranchNameTemplate = (
  template: string,
  ctx: { slug: string; timestamp: string }
): string => {
  const replaced = template
    .replace(/\{slug\}/g, ctx.slug)
    .replace(/\{timestamp\}/g, ctx.timestamp);
  return sanitizeBranchName(replaced);
};

import LinearSetupForm from './integrations/LinearSetupForm';
import JiraSetupForm from './integrations/JiraSetupForm';
import { LinearIssueSelector } from './LinearIssueSelector';
import { GitHubIssueSelector } from './GitHubIssueSelector';
import JiraIssueSelector from './JiraIssueSelector';
import { type JiraIssueSummary } from '../types/jira';
import { useGithubAuth } from '../hooks/useGithubAuth';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateTask: (
    name: string,
    initialPrompt?: string,
    providerRuns?: ProviderRun[],
    linkedLinearIssue?: LinearIssueSummary | null,
    linkedGithubIssue?: GitHubIssueSummary | null,
    linkedJiraIssue?: import('../types/jira').JiraIssueSummary | null,
    autoApprove?: boolean
  ) => void;
  projectName: string;
  defaultBranch: string;
  existingNames?: string[];
  projectPath?: string;
}

const TaskModal: React.FC<TaskModalProps> = ({
  isOpen,
  onClose,
  onCreateTask,
  projectName,
  defaultBranch,
  existingNames = [],
  projectPath,
}) => {
  const [taskName, setTaskName] = useState('');
  const [defaultProviderFromSettings, setDefaultProviderFromSettings] =
    useState<Provider>(DEFAULT_PROVIDER);
  const [providerRuns, setProviderRuns] = useState<ProviderRun[]>([
    { provider: DEFAULT_PROVIDER, runs: 1 },
  ]);
  const [autoGeneratedName, setAutoGeneratedName] = useState<string>('');
  const [customNameTracked, setCustomNameTracked] = useState(false);
  const userHasTypedRef = useRef(false);
  const isInitialSetupRef = useRef(true);
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);
  const [initialPrompt, setInitialPrompt] = useState('');
  const [selectedLinearIssue, setSelectedLinearIssue] = useState<LinearIssueSummary | null>(null);
  const [selectedGithubIssue, setSelectedGithubIssue] = useState<GitHubIssueSummary | null>(null);

  const [selectedJiraIssue, setSelectedJiraIssue] = useState<JiraIssueSummary | null>(null);
  const [isJiraConnected, setIsJiraConnected] = useState<boolean | null>(null);
  const [isLinearConnected, setIsLinearConnected] = useState<boolean | null>(null);
  const [linearSetupOpen, setLinearSetupOpen] = useState(false);
  const [linearApiKey, setLinearApiKey] = useState('');
  const [linearConnectionError, setLinearConnectionError] = useState<string | null>(null);
  const [autoOpenLinearSelector, setAutoOpenLinearSelector] = useState(false);
  const [jiraSetupOpen, setJiraSetupOpen] = useState(false);
  const [jiraSite, setJiraSite] = useState('');
  const [jiraEmail, setJiraEmail] = useState('');
  const [jiraToken, setJiraToken] = useState('');
  const [jiraConnectionError, setJiraConnectionError] = useState<string | null>(null);
  const [autoApprove, setAutoApprove] = useState(false);
  const autoNameInitializedRef = useRef(false);
  const [branchTemplate, setBranchTemplate] = useState(DEFAULT_BRANCH_TEMPLATE);
  const [isEditingHeader, setIsEditingHeader] = useState(false);
  const [activeAttachment, setActiveAttachment] = useState<'linear' | 'github' | 'jira' | null>(
    null
  );
  const promptRef = useRef<HTMLTextAreaElement>(null);
  const headerInputRef = useRef<HTMLInputElement>(null);
  const branchTimestampRef = useRef<number>(Date.now());

  // GitHub connection state
  const {
    installed: githubInstalled,
    authenticated: githubAuthenticated,
    login: githubLogin,
    isLoading: githubLoading,
  } = useGithubAuth();
  const isGithubConnected = githubInstalled && githubAuthenticated;

  // Computed values
  const activeProviders = useMemo(() => providerRuns.map((pr) => pr.provider), [providerRuns]);
  const hasAutoApproveSupport =
    activeProviders.length > 0 &&
    activeProviders.every((providerId) => !!providerMeta[providerId]?.autoApproveFlag);
  const hasInitialPromptSupport =
    activeProviders.length > 0 &&
    activeProviders.every(
      (providerId) => providerMeta[providerId]?.initialPromptFlag !== undefined
    );
  const shouldReduceMotion = useReducedMotion();
  const normalizedTaskName = useMemo(() => normalizeTaskName(taskName), [taskName]);
  const promptPlaceholder = useMemo(() => {
    if (!hasInitialPromptSupport) {
      return 'Selected provider does not support initial prompts';
    }
    if (selectedLinearIssue) {
      return `e.g. Fix the attached Linear ticket ${selectedLinearIssue.identifier} — describe any constraints.`;
    }
    if (selectedGithubIssue) {
      return `e.g. Fix the attached GitHub issue #${selectedGithubIssue.number} — describe any constraints.`;
    }
    if (selectedJiraIssue) {
      return `e.g. Fix the attached Jira ticket ${selectedJiraIssue.key} — describe any constraints.`;
    }
    return 'Describe the task or changes you want to make...';
  }, [
    hasInitialPromptSupport,
    selectedLinearIssue,
    selectedGithubIssue,
    selectedJiraIssue,
  ]);

  useEffect(() => {
    if (!promptRef.current) return;
    promptRef.current.style.height = 'auto';
    promptRef.current.style.height = `${promptRef.current.scrollHeight}px`;
  }, [initialPrompt]);

  useEffect(() => {
    if (isEditingHeader) {
      headerInputRef.current?.focus();
    }
  }, [isEditingHeader]);

  // Clear issues and prompt when provider changes to one without support
  useEffect(() => {
    if (!hasInitialPromptSupport) {
      setSelectedLinearIssue(null);
      setSelectedGithubIssue(null);
      setSelectedJiraIssue(null);
      setInitialPrompt('');
      setActiveAttachment(null);
    }
  }, [hasInitialPromptSupport]);

  const normalizedExisting = useMemo(
    () => existingNames.map((n) => normalizeTaskName(n)).filter(Boolean),
    [existingNames]
  );

  const validate = useCallback(
    (value: string): string | null => {
      const normalized = normalizeTaskName(value);
      if (!normalized) return 'Please enter a Task name.';
      if (normalizedExisting.includes(normalized)) {
        return 'A Task with this name already exists.';
      }
      if (normalized.length > MAX_TASK_NAME_LENGTH) {
        return `Task name is too long (max ${MAX_TASK_NAME_LENGTH} characters).`;
      }
      return null;
    },
    [normalizedExisting]
  );

  const onChange = (val: string) => {
    setTaskName(val);
    setError(validate(val));
    // Track that user has manually edited the name (not during initial setup)
    if (!isInitialSetupRef.current) {
      userHasTypedRef.current = true;
    }
    // Track custom naming when user manually changes from auto-generated name (once)
    if (
      !customNameTracked &&
      autoGeneratedName &&
      val !== autoGeneratedName &&
      val.trim() &&
      normalizeTaskName(val) !== normalizeTaskName(autoGeneratedName)
    ) {
      setCustomNameTracked(true);
      void (async () => {
        const { captureTelemetry } = await import('../lib/telemetryClient');
        captureTelemetry('task_custom_named', { custom_name: 'true' });
      })();
    }
  };

  useEffect(() => {
    if (!isOpen) return;

    // Reset all form state on open
    setTaskName('');
    setAutoGeneratedName('');
    setError(null);
    setTouched(false);
    setCustomNameTracked(false);
    setInitialPrompt('');
    setSelectedLinearIssue(null);
    setSelectedGithubIssue(null);
    setSelectedJiraIssue(null);
    setAutoApprove(false);
    setLinearSetupOpen(false);
    setLinearApiKey('');
    setLinearConnectionError(null);
    setAutoOpenLinearSelector(false);
    setJiraSetupOpen(false);
    setJiraSite('');
    setJiraEmail('');
    setJiraToken('');
    setJiraConnectionError(null);
    setBranchTemplate(DEFAULT_BRANCH_TEMPLATE);
    setIsEditingHeader(false);
    setActiveAttachment(null);
    branchTimestampRef.current = Date.now();
    userHasTypedRef.current = false;
    isInitialSetupRef.current = false; // allow typing to mark userHasTyped immediately
    autoNameInitializedRef.current = false;

    // Generate auto-generated name synchronously to avoid race condition.
    const suggested = generateFriendlyTaskName(normalizedExisting);
    const applySuggestedName = () => {
      if (userHasTypedRef.current) return;
      setAutoGeneratedName(suggested);
      setTaskName((prev) => {
        if (prev) return prev;
        setError(validate(suggested));
        return suggested;
      });
      autoNameInitializedRef.current = true;
    };
    applySuggestedName();

    let cancel = false;
    window.electronAPI.getSettings().then((res) => {
      if (cancel) return;
      const settings = res?.success ? res.settings : undefined;

      // Provider
      const settingsProvider = settings?.defaultProvider;
      const defaultProvider: Provider = isValidProviderId(settingsProvider)
        ? (settingsProvider as Provider)
        : DEFAULT_PROVIDER;
      setDefaultProviderFromSettings(defaultProvider);
      setProviderRuns([{ provider: defaultProvider, runs: 1 }]);

      // Branch template
      const repoTemplate = settings?.repository?.branchTemplate;
      setBranchTemplate(
        typeof repoTemplate === 'string' && repoTemplate.trim()
          ? repoTemplate
          : DEFAULT_BRANCH_TEMPLATE
      );

      // Auto-approve default
      const autoApproveByDefault = settings?.tasks?.autoApproveByDefault ?? false;
      setAutoApprove(autoApproveByDefault && !!providerMeta[defaultProvider]?.autoApproveFlag);

      // Auto-generate task name
      // Only update if user hasn't typed yet
      const autoGenerate = settings?.tasks?.autoGenerateName ?? true;
      if (!autoNameInitializedRef.current && !userHasTypedRef.current && !taskName) {
        if (!autoGenerate) {
          // User disabled auto-generate, clear the name
          setAutoGeneratedName('');
          setTaskName('');
          setError(null);
        } else {
          // Ensure auto-generated name is set (may have been cleared by user typing)
          setAutoGeneratedName(suggested);
          setTaskName((prev) => {
            if (prev) return prev;
            setError(validate(suggested));
            return suggested;
          });
        }
        autoNameInitializedRef.current = true;
      }
    });
    return () => {
      cancel = true;
    };
  }, [isOpen]);

  // Check Linear connection when modal opens
  useEffect(() => {
    if (!isOpen) return;
    let cancel = false;
    const api: any = (window as any).electronAPI;
    if (!api?.linearCheckConnection) {
      setIsLinearConnected(false);
      return;
    }
    api
      .linearCheckConnection()
      .then((res: any) => {
        if (!cancel) setIsLinearConnected(!!res?.connected);
      })
      .catch(() => {
        if (!cancel) setIsLinearConnected(false);
      });
    return () => {
      cancel = true;
    };
  }, [isOpen]);

  // Check Jira connection when modal opens
  useEffect(() => {
    if (!isOpen) return;
    let cancel = false;
    const api: any = (window as any).electronAPI;
    api
      ?.jiraCheckConnection?.()
      .then((res: any) => {
        if (!cancel) setIsJiraConnected(!!res?.connected);
      })
      .catch(() => {
        if (!cancel) setIsJiraConnected(false);
      });
    return () => {
      cancel = true;
    };
  }, [isOpen]);

  const handleLinearConnect = useCallback(async () => {
    const trimmedKey = linearApiKey.trim();
    if (!trimmedKey || !window?.electronAPI?.linearSaveToken) {
      return;
    }

    setLinearConnectionError(null);
    try {
      const result = await window.electronAPI.linearSaveToken(trimmedKey);
      if (result?.success) {
        setIsLinearConnected(true);
        setLinearSetupOpen(false);
        setLinearApiKey('');
        setLinearConnectionError(null);
        setAutoOpenLinearSelector(true);
      } else {
        setLinearConnectionError(result?.error || 'Could not connect Linear. Try again.');
      }
    } catch (error) {
      console.error('Linear connect failed:', error);
      setLinearConnectionError('Could not connect Linear. Try again.');
    }
  }, [linearApiKey]);

  const handleGithubConnect = useCallback(async () => {
    if (!githubInstalled) {
      try {
        await window.electronAPI.openExternal('https://cli.github.com/manual/installation');
      } catch (error) {
        console.error('Failed to open GitHub CLI install docs:', error);
      }
      return;
    }
    try {
      const result = await githubLogin();
      if (result?.success) {
        // Connection status will update via useGithubAuth hook
      }
    } catch (error) {
      console.error('GitHub connect failed:', error);
    }
  }, [githubInstalled, githubLogin]);

  const handleJiraConnect = useCallback(async () => {
    try {
      setJiraConnectionError(null);
      const api: any = (window as any).electronAPI;
      const res = await api?.jiraSaveCredentials?.({
        siteUrl: jiraSite.trim(),
        email: jiraEmail.trim(),
        token: jiraToken.trim(),
      });
      if (res?.success) {
        setIsJiraConnected(true);
        setJiraSite('');
        setJiraEmail('');
        setJiraToken('');
        setJiraSetupOpen(false);
        setJiraConnectionError(null);
      } else {
        setJiraConnectionError(res?.error || 'Failed to connect.');
      }
    } catch (e: any) {
      setJiraConnectionError(e?.message || 'Failed to connect.');
    }
  }, [jiraSite, jiraEmail, jiraToken]);

  useEffect(() => {
    if (!hasAutoApproveSupport && autoApprove) {
      setAutoApprove(false);
    }
  }, [hasAutoApproveSupport, autoApprove]);

  const displayTaskName = taskName.trim() ? taskName : 'New Task';
  const branchSlug = slugifyBranchName(normalizedTaskName || 'task');
  const displayBranchName = renderBranchNameTemplate(branchTemplate, {
    slug: branchSlug || slugifyBranchName('task'),
    timestamp: String(branchTimestampRef.current),
  });
  const nameHasError = touched && !!error;
  const canToggleAutoApprove = hasAutoApproveSupport;
  const attachmentsDisabled = !hasInitialPromptSupport;

  const toggleAttachment = useCallback((next: 'linear' | 'github' | 'jira') => {
    setActiveAttachment((prev) => (prev === next ? null : next));
  }, []);

  const handleSubmit = useCallback(() => {
    setTouched(true);
    // User is intentionally submitting; prevent any late auto-generate overrides
    userHasTypedRef.current = true;
    autoNameInitializedRef.current = true;
    const err = validate(taskName);
    if (err) {
      setError(err);
      return;
    }
    setIsCreating(true);
    (async () => {
      try {
        const trimmedPrompt = initialPrompt.trim();
        await onCreateTask(
          normalizedTaskName,
          hasInitialPromptSupport && trimmedPrompt ? trimmedPrompt : undefined,
          providerRuns,
          selectedLinearIssue,
          selectedGithubIssue,
          selectedJiraIssue,
          hasAutoApproveSupport ? autoApprove : false
        );
        onClose();
      } catch (error) {
        console.error('Failed to create task:', error);
      } finally {
        setIsCreating(false);
      }
    })();
  }, [
    autoApprove,
    hasAutoApproveSupport,
    hasInitialPromptSupport,
    initialPrompt,
    normalizedTaskName,
    onClose,
    onCreateTask,
    providerRuns,
    selectedGithubIssue,
    selectedJiraIssue,
    selectedLinearIssue,
    taskName,
    validate,
  ]);

  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <motion.div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 font-sans"
          initial={shouldReduceMotion ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={shouldReduceMotion ? { opacity: 1 } : { opacity: 0 }}
          transition={shouldReduceMotion ? { duration: 0 } : { duration: 0.1, ease: 'easeOut' }}
          onClick={onClose}
        >
          <motion.div
            onClick={(e) => e.stopPropagation()}
            initial={shouldReduceMotion ? false : { opacity: 0, y: 10, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={
              shouldReduceMotion
                ? { opacity: 1, y: 0, scale: 1 }
                : { opacity: 0, y: 10, scale: 0.98 }
            }
            transition={
              shouldReduceMotion ? { duration: 0 } : { duration: 0.2, ease: [0.22, 1, 0.36, 1] }
            }
            className="w-full max-w-2xl"
          >
            <Card
              className="relative flex w-full flex-col overflow-visible rounded-2xl border border-white/10 bg-[#09090b] shadow-2xl shadow-black/50 ring-1 ring-white/5"
            >
              <CardHeader className="flex flex-row items-center justify-between space-y-0 border-b border-white/5 bg-white/[0.02] px-4 py-3">
                <div className="flex min-w-0 flex-1 items-center gap-2 pr-4">
                  {isEditingHeader ? (
                    <div className="flex flex-1 items-center gap-2 animate-in fade-in duration-200">
                      <div className="relative flex-1 max-w-[220px]">
                        <Hash
                          size={12}
                          className="absolute left-2.5 top-1/2 -translate-y-1/2 text-zinc-500"
                        />
                        <Input
                          ref={headerInputRef}
                          value={taskName}
                          onChange={(e) => onChange(e.target.value)}
                          onBlur={() => setTouched(true)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              e.preventDefault();
                              setIsEditingHeader(false);
                            }
                          }}
                          placeholder="Task name"
                          aria-label="Task name"
                          aria-invalid={nameHasError}
                          aria-describedby="task-name-error"
                          className={`h-8 border ${
                            nameHasError
                              ? 'border-red-500/60 focus-visible:border-red-500 focus-visible:ring-red-500/30'
                              : 'border-blue-500/30 focus-visible:border-blue-500 focus-visible:ring-blue-500/30'
                          } bg-black/40 px-2 py-1 pl-7 text-sm text-white focus-visible:ring-1`}
                        />
                      </div>
                      <span className="text-zinc-600">/</span>
                      <div className="relative flex-1 max-w-[220px]">
                        <GitBranch
                          size={12}
                          className="absolute left-2.5 top-1/2 -translate-y-1/2 text-zinc-500"
                        />
                        <Input
                          value={displayBranchName}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              e.preventDefault();
                              setIsEditingHeader(false);
                            }
                          }}
                          placeholder="branch-name"
                          aria-label="Branch name"
                          readOnly
                          className="h-8 border border-blue-500/30 bg-black/40 px-2 py-1 pl-7 text-xs font-mono text-zinc-300 focus-visible:border-blue-500 focus-visible:ring-1 focus-visible:ring-blue-500/30"
                        />
                      </div>
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => setIsEditingHeader(false)}
                        className="h-8 w-8 rounded-md text-green-400 hover:bg-green-400/10 hover:text-green-300"
                      >
                        <ArrowUp size={14} />
                      </Button>
                    </div>
                  ) : (
                    <button
                      type="button"
                      onClick={() => setIsEditingHeader(true)}
                      className="flex items-center gap-2 text-sm text-zinc-400 hover:bg-white/5 px-2 py-1 rounded-md transition-colors group text-left truncate"
                      title="Click to edit Task & Branch"
                    >
                      <span className="flex items-center justify-center w-6 h-6 rounded bg-blue-500/10 text-blue-400 shrink-0">
                        <Sparkles size={14} />
                      </span>
                      <span className="font-medium text-zinc-200 truncate">{displayTaskName}</span>
                      <span className="text-zinc-600 shrink-0">•</span>
                      <span className="font-mono text-xs text-zinc-500 flex items-center gap-1 truncate">
                        <GitBranch size={10} />
                        {displayBranchName}
                      </span>
                      <Pencil className="ml-1 h-3 w-3 opacity-0 text-zinc-500 transition-opacity group-hover:opacity-100" />
                    </button>
                  )}
                </div>

                <div className="flex items-center gap-1 shrink-0">
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    onClick={onClose}
                    className="h-8 w-8 rounded-md text-zinc-500 hover:bg-white/5 hover:text-red-400"
                  >
                    <X size={16} />
                  </Button>
                </div>

                <div className="sr-only">
                  <CardTitle>New Task</CardTitle>
                  <CardDescription>
                    {projectName} • from origin/{defaultBranch}
                  </CardDescription>
                </div>
              </CardHeader>

              <CardContent className="flex flex-1 flex-col p-0">
                <Separator className="sr-only" />
                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    handleSubmit();
                  }}
                  className="flex flex-1 flex-col"
                >
                  <div className="flex flex-col w-full min-h-[160px]">
                    <div className="relative flex-1 p-5">
                      <textarea
                        ref={promptRef}
                        value={initialPrompt}
                        onChange={(e) => setInitialPrompt(e.target.value)}
                        placeholder={promptPlaceholder}
                        className={`w-full h-full min-h-[120px] bg-transparent text-lg text-zinc-100 placeholder:text-zinc-600 focus:outline-none resize-none leading-relaxed selection:bg-blue-500/30 ${
                          !hasInitialPromptSupport ? 'opacity-50' : ''
                        }`}
                        autoFocus
                        spellCheck={false}
                        disabled={!hasInitialPromptSupport}
                      />
                    </div>
                  </div>

                  {nameHasError ? (
                    <p id="task-name-error" className="px-5 pb-1 text-xs text-red-400">
                      {error}
                    </p>
                  ) : null}

                  <div className="relative z-10 flex flex-col border-t border-white/5 bg-zinc-900/50">
                    <div className="flex flex-wrap items-center gap-2 px-4 pt-3">
                      <button
                        type="button"
                        onClick={() => setActiveAttachment(null)}
                        className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-zinc-300 transition-colors hover:bg-white/[0.06]"
                      >
                        <FileUp size={14} className="text-current" />
                        Upload File
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (!attachmentsDisabled) {
                            toggleAttachment('linear');
                          }
                        }}
                        disabled={attachmentsDisabled}
                        aria-pressed={activeAttachment === 'linear'}
                        className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                          attachmentsDisabled
                            ? 'border-white/10 bg-white/[0.03] text-zinc-500 opacity-50 cursor-not-allowed'
                            : activeAttachment === 'linear'
                              ? 'border-blue-500/40 bg-blue-500/10 text-blue-200'
                              : selectedLinearIssue
                                ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-200'
                                : 'border-white/10 bg-white/[0.03] text-zinc-300 hover:bg-white/[0.06]'
                        }`}
                      >
                        <span className="flex h-4 w-4 items-center justify-center rounded-full border border-current text-[9px] font-semibold">
                          L
                        </span>
                        Linear Issue
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (!attachmentsDisabled) {
                            toggleAttachment('github');
                          }
                        }}
                        disabled={attachmentsDisabled}
                        aria-pressed={activeAttachment === 'github'}
                        className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                          attachmentsDisabled
                            ? 'border-white/10 bg-white/[0.03] text-zinc-500 opacity-50 cursor-not-allowed'
                            : activeAttachment === 'github'
                              ? 'border-blue-500/40 bg-blue-500/10 text-blue-200'
                              : selectedGithubIssue
                                ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-200'
                                : 'border-white/10 bg-white/[0.03] text-zinc-300 hover:bg-white/[0.06]'
                        }`}
                      >
                        <Github size={14} className="text-current" />
                        GitHub Issue
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (!attachmentsDisabled) {
                            toggleAttachment('jira');
                          }
                        }}
                        disabled={attachmentsDisabled}
                        aria-pressed={activeAttachment === 'jira'}
                        className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                          attachmentsDisabled
                            ? 'border-white/10 bg-white/[0.03] text-zinc-500 opacity-50 cursor-not-allowed'
                            : activeAttachment === 'jira'
                              ? 'border-blue-500/40 bg-blue-500/10 text-blue-200'
                              : selectedJiraIssue
                                ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-200'
                                : 'border-white/10 bg-white/[0.03] text-zinc-300 hover:bg-white/[0.06]'
                        }`}
                      >
                        <Trello size={14} className="text-current" />
                        Jira Ticket
                      </button>
                    </div>

                    <AnimatePresence>
                      {activeAttachment ? (
                        <motion.div
                          initial={shouldReduceMotion ? false : { opacity: 0, y: -6 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={
                            shouldReduceMotion ? { opacity: 1, y: 0 } : { opacity: 0, y: -6 }
                          }
                          transition={
                            shouldReduceMotion
                              ? { duration: 0 }
                              : { duration: 0.2, ease: [0.22, 1, 0.36, 1] }
                          }
                          className="px-4 pb-3"
                        >
                          <div className="space-y-4 rounded-xl border border-white/10 bg-black/40 p-4">
                            {activeAttachment === 'linear' ? (
                              <div className="flex items-start gap-4">
                                <Label
                                  htmlFor="linear-issue"
                                  className="w-32 shrink-0 pt-2 text-zinc-300"
                                >
                                  Linear issue
                                </Label>
                                <div className="flex min-w-0 flex-1 items-center gap-2">
                                  <LinearIssueSelector
                                    selectedIssue={selectedLinearIssue}
                                    onIssueChange={(issue) => {
                                      setSelectedLinearIssue(issue);
                                      if (issue) {
                                        setSelectedGithubIssue(null);
                                        setSelectedJiraIssue(null);
                                      }
                                    }}
                                    isOpen={isOpen}
                                    disabled={
                                      !hasInitialPromptSupport ||
                                      !isLinearConnected ||
                                      !!selectedGithubIssue ||
                                      !!selectedJiraIssue
                                    }
                                    className="w-full"
                                    autoOpen={autoOpenLinearSelector}
                                    onAutoOpenHandled={() => setAutoOpenLinearSelector(false)}
                                    placeholder={
                                      isLinearConnected ? 'Select a Linear issue' : 'Select issue'
                                    }
                                  />
                                  {!isLinearConnected && (
                                    <Button
                                      type="button"
                                      size="sm"
                                      variant="outline"
                                      className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                      onClick={() => setLinearSetupOpen(true)}
                                    >
                                      Connect
                                    </Button>
                                  )}
                                </div>
                                <AnimatePresence>
                                  {linearSetupOpen ? (
                                    <motion.div
                                      className="fixed inset-0 z-[130] flex items-center justify-center px-3"
                                      initial={{ opacity: 0 }}
                                      animate={{ opacity: 1 }}
                                      exit={{ opacity: 0 }}
                                      onClick={() => setLinearSetupOpen(false)}
                                    >
                                      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                                      <motion.div
                                        className="relative z-10 w-full max-w-md rounded-xl border border-border/70 bg-background/95 p-4 shadow-2xl backdrop-blur-sm"
                                        initial={{ opacity: 0, scale: 0.95 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        exit={{ opacity: 0, scale: 0.95 }}
                                        transition={{ duration: shouldReduceMotion ? 0 : 0.15 }}
                                        onClick={(event) => event.stopPropagation()}
                                      >
                                        <LinearSetupForm
                                          apiKey={linearApiKey}
                                          onChange={(value) => setLinearApiKey(value)}
                                          onSubmit={() => void handleLinearConnect()}
                                          onClose={() => setLinearSetupOpen(false)}
                                          canSubmit={!!linearApiKey.trim()}
                                          error={linearConnectionError}
                                        />
                                      </motion.div>
                                    </motion.div>
                                  ) : null}
                                </AnimatePresence>
                              </div>
                            ) : null}

                            {activeAttachment === 'github' ? (
                              <div className="flex items-start gap-4">
                                <Label
                                  htmlFor="github-issue"
                                  className="w-32 shrink-0 pt-2 text-zinc-300"
                                >
                                  GitHub issue
                                </Label>
                                <div className="flex min-w-0 flex-1 items-center gap-2">
                                  <GitHubIssueSelector
                                    projectPath={projectPath || ''}
                                    selectedIssue={selectedGithubIssue}
                                    onIssueChange={(issue) => {
                                      setSelectedGithubIssue(issue);
                                      if (issue) {
                                        setSelectedLinearIssue(null);
                                        setSelectedJiraIssue(null);
                                      }
                                    }}
                                    isOpen={isOpen}
                                    disabled={
                                      !hasInitialPromptSupport ||
                                      !isGithubConnected ||
                                      !!selectedJiraIssue ||
                                      !!selectedLinearIssue
                                    }
                                    className="w-full"
                                    placeholder={
                                      isGithubConnected ? 'Select a GitHub issue' : 'Select issue'
                                    }
                                  />
                                  {!isGithubConnected && (
                                    <Button
                                      type="button"
                                      size="sm"
                                      variant="outline"
                                      className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                      onClick={() => void handleGithubConnect()}
                                      disabled={githubLoading}
                                    >
                                      {githubLoading ? (
                                        <>
                                          <Spinner size="sm" className="mr-1" />
                                          Connecting...
                                        </>
                                      ) : !githubInstalled ? (
                                        'Install CLI'
                                      ) : (
                                        'Connect'
                                      )}
                                    </Button>
                                  )}
                                </div>
                              </div>
                            ) : null}

                            {activeAttachment === 'jira' ? (
                              <div className="flex items-start gap-4">
                                <Label
                                  htmlFor="jira-issue"
                                  className="w-32 shrink-0 pt-2 text-zinc-300"
                                >
                                  Jira issue
                                </Label>
                                <div className="flex min-w-0 flex-1 items-center gap-2">
                                  <JiraIssueSelector
                                    selectedIssue={selectedJiraIssue}
                                    onIssueChange={(issue) => {
                                      setSelectedJiraIssue(issue);
                                      if (issue) {
                                        setSelectedLinearIssue(null);
                                        setSelectedGithubIssue(null);
                                      }
                                    }}
                                    isOpen={isOpen}
                                    disabled={
                                      !hasInitialPromptSupport ||
                                      !isJiraConnected ||
                                      !!selectedLinearIssue ||
                                      !!selectedGithubIssue
                                    }
                                    className="w-full"
                                    placeholder={
                                      isJiraConnected ? 'Select a Jira issue' : 'Select issue'
                                    }
                                  />
                                  {!isJiraConnected && (
                                    <Button
                                      type="button"
                                      size="sm"
                                      variant="outline"
                                      className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                      onClick={() => setJiraSetupOpen(true)}
                                    >
                                      Connect
                                    </Button>
                                  )}
                                </div>
                                <AnimatePresence>
                                  {jiraSetupOpen ? (
                                    <motion.div
                                      className="fixed inset-0 z-[130] flex items-center justify-center px-3"
                                      initial={{ opacity: 0 }}
                                      animate={{ opacity: 1 }}
                                      exit={{ opacity: 0 }}
                                      onClick={() => setJiraSetupOpen(false)}
                                    >
                                      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                                      <motion.div
                                        className="relative z-10 w-full max-w-md rounded-xl border border-border/70 bg-background/95 p-4 shadow-2xl backdrop-blur-sm"
                                        initial={{ opacity: 0, scale: 0.95 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        exit={{ opacity: 0, scale: 0.95 }}
                                        transition={{ duration: shouldReduceMotion ? 0 : 0.15 }}
                                        onClick={(event) => event.stopPropagation()}
                                      >
                                        <JiraSetupForm
                                          site={jiraSite}
                                          email={jiraEmail}
                                          token={jiraToken}
                                          onChange={(u) => {
                                            if (typeof u.site === 'string') setJiraSite(u.site);
                                            if (typeof u.email === 'string') setJiraEmail(u.email);
                                            if (typeof u.token === 'string') setJiraToken(u.token);
                                          }}
                                          onClose={() => setJiraSetupOpen(false)}
                                          canSubmit={
                                            !!(
                                              jiraSite.trim() &&
                                              jiraEmail.trim() &&
                                              jiraToken.trim()
                                            )
                                          }
                                          error={jiraConnectionError}
                                          onSubmit={() => void handleJiraConnect()}
                                        />
                                      </motion.div>
                                    </motion.div>
                                  ) : null}
                                </AnimatePresence>
                              </div>
                            ) : null}
                          </div>
                        </motion.div>
                      ) : null}
                    </AnimatePresence>

                    <div className="flex items-center justify-between px-4 py-3 gap-3">
                      <div className="flex items-center gap-3">
                        <div className="relative">
                          <MultiProviderDropdown
                            providerRuns={providerRuns}
                            onChange={setProviderRuns}
                            defaultProvider={defaultProviderFromSettings}
                            className="!h-7 !w-auto !rounded-full !border !border-white/5 !bg-white/5 !px-3 !text-xs !text-zinc-300 hover:!bg-white/10 hover:!border-white/10"
                          />
                        </div>

                        <div className="h-4 w-px bg-white/10 mx-1" />

                        <button
                          type="button"
                          onClick={() => {
                            if (canToggleAutoApprove) {
                              setAutoApprove(!autoApprove);
                            }
                          }}
                          disabled={!canToggleAutoApprove}
                          className={`flex items-center gap-2 px-2 py-1.5 rounded-md transition-all border ${
                            canToggleAutoApprove
                              ? autoApprove
                                ? 'bg-red-500/10 border-red-500/20 text-red-400 hover:bg-red-500/20'
                                : 'bg-transparent border-transparent text-zinc-500 hover:text-zinc-300 hover:bg-white/5'
                              : 'border-transparent text-zinc-500 opacity-50 cursor-not-allowed'
                          }`}
                          title={
                            canToggleAutoApprove
                              ? autoApprove
                                ? 'Permissions skipped (Unsafe)'
                                : 'Permissions active (Safe)'
                              : 'Selected provider does not support auto-approve'
                          }
                        >
                          {autoApprove ? <ShieldAlert size={16} /> : <Shield size={16} />}
                          <span className="text-xs font-medium">
                            {autoApprove ? 'Unrestricted' : 'Safe Mode'}
                          </span>
                        </button>
                      </div>

                      <div className="flex items-center gap-3">
                        <Button
                          type="submit"
                          disabled={!!validate(taskName) || isCreating}
                          className="flex items-center gap-2 pl-4 pr-3 py-2 text-sm font-semibold transition-all bg-blue-600 rounded-xl text-white hover:bg-blue-500 disabled:opacity-50 disabled:hover:bg-blue-600 shadow-[0_0_15px_rgba(37,99,235,0.3)] hover:shadow-[0_0_20px_rgba(37,99,235,0.5)] active:scale-95"
                        >
                          {isCreating ? (
                            <>
                              <Spinner size="sm" className="mr-2" />
                              Creating...
                            </>
                          ) : (
                            <>
                              Create Task
                              <div className="flex items-center justify-center w-5 h-5 bg-white/20 rounded-md">
                                <ArrowUp size={12} strokeWidth={3} />
                              </div>
                            </>
                          )}
                        </Button>
                      </div>
                    </div>
                  </div>
                </form>
              </CardContent>
            </Card>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );

};

export default TaskModal;
