import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Spinner } from './ui/spinner';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { X, GitBranch, ExternalLink, Settings } from 'lucide-react';
import { MultiProviderDropdown } from './MultiProviderDropdown';
import { type Provider } from '../types';
import { type ProviderRun } from '../types/chat';
import { Separator } from './ui/separator';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './ui/tooltip';
import { providerMeta } from '../providers/meta';
import { isValidProviderId } from '@shared/providers/registry';
import { type LinearIssueSummary } from '../types/linear';
import { type GitHubIssueSummary } from '../types/github';
import {
  generateFriendlyWorkspaceName,
  normalizeWorkspaceName,
  MAX_WORKSPACE_NAME_LENGTH,
} from '../lib/workspaceNames';

const DEFAULT_PROVIDER: Provider = 'claude';

import LinearSetupForm from './integrations/LinearSetupForm';
import JiraSetupForm from './integrations/JiraSetupForm';
import { LinearIssueSelector } from './LinearIssueSelector';
import { GitHubIssueSelector } from './GitHubIssueSelector';
import JiraIssueSelector from './JiraIssueSelector';
import { type JiraIssueSummary } from '../types/jira';
import { useGithubAuth } from '../hooks/useGithubAuth';

interface WorkspaceModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateWorkspace: (
    name: string,
    initialPrompt?: string,
    providerRuns?: ProviderRun[],
    linkedLinearIssue?: LinearIssueSummary | null,
    linkedGithubIssue?: GitHubIssueSummary | null,
    linkedJiraIssue?: import('../types/jira').JiraIssueSummary | null,
    autoApprove?: boolean
  ) => void;
  projectName: string;
  defaultBranch: string;
  existingNames?: string[];
  projectPath?: string;
}

const WorkspaceModal: React.FC<WorkspaceModalProps> = ({
  isOpen,
  onClose,
  onCreateWorkspace,
  projectName,
  defaultBranch,
  existingNames = [],
  projectPath,
}) => {
  const [workspaceName, setWorkspaceName] = useState('');
  const [defaultProviderFromSettings, setDefaultProviderFromSettings] =
    useState<Provider>(DEFAULT_PROVIDER);
  const [providerRuns, setProviderRuns] = useState<ProviderRun[]>([
    { provider: DEFAULT_PROVIDER, runs: 1 },
  ]);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState<string>('');
  const [customNameTracked, setCustomNameTracked] = useState(false);
  const userHasTypedRef = useRef(false);
  const isInitialSetupRef = useRef(true);
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);
  const [initialPrompt, setInitialPrompt] = useState('');
  const [selectedLinearIssue, setSelectedLinearIssue] = useState<LinearIssueSummary | null>(null);
  const [selectedGithubIssue, setSelectedGithubIssue] = useState<GitHubIssueSummary | null>(null);

  const [selectedJiraIssue, setSelectedJiraIssue] = useState<JiraIssueSummary | null>(null);
  const [isJiraConnected, setIsJiraConnected] = useState<boolean | null>(null);
  const [isLinearConnected, setIsLinearConnected] = useState<boolean | null>(null);
  const [linearSetupOpen, setLinearSetupOpen] = useState(false);
  const [linearApiKey, setLinearApiKey] = useState('');
  const [linearConnectionError, setLinearConnectionError] = useState<string | null>(null);
  const [autoOpenLinearSelector, setAutoOpenLinearSelector] = useState(false);
  const [jiraSetupOpen, setJiraSetupOpen] = useState(false);
  const [jiraSite, setJiraSite] = useState('');
  const [jiraEmail, setJiraEmail] = useState('');
  const [jiraToken, setJiraToken] = useState('');
  const [jiraConnectionError, setJiraConnectionError] = useState<string | null>(null);
  const [autoApprove, setAutoApprove] = useState(false);

  // GitHub connection state
  const {
    installed: githubInstalled,
    authenticated: githubAuthenticated,
    login: githubLogin,
    isLoading: githubLoading,
  } = useGithubAuth();
  const isGithubConnected = githubInstalled && githubAuthenticated;

  // Computed values
  const activeProviders = useMemo(() => providerRuns.map((pr) => pr.provider), [providerRuns]);
  const hasAutoApproveSupport =
    activeProviders.length > 0 &&
    activeProviders.every((providerId) => !!providerMeta[providerId]?.autoApproveFlag);
  const hasInitialPromptSupport =
    activeProviders.length > 0 &&
    activeProviders.every(
      (providerId) => providerMeta[providerId]?.initialPromptFlag !== undefined
    );
  const shouldReduceMotion = useReducedMotion();

  // Clear issues and prompt when provider changes to one without support
  useEffect(() => {
    if (!hasInitialPromptSupport) {
      setSelectedLinearIssue(null);
      setSelectedGithubIssue(null);
      setSelectedJiraIssue(null);
      setInitialPrompt('');
    }
  }, [hasInitialPromptSupport]);

  const normalizedExisting = useMemo(
    () => existingNames.map((n) => normalizeWorkspaceName(n)).filter(Boolean),
    [existingNames]
  );

  const validate = useCallback(
    (value: string): string | null => {
      const normalized = normalizeWorkspaceName(value);
      if (!normalized) return 'Please enter a Task name.';
      if (normalizedExisting.includes(normalized)) {
        return 'A Task with this name already exists.';
      }
      if (normalized.length > MAX_WORKSPACE_NAME_LENGTH) {
        return `Task name is too long (max ${MAX_WORKSPACE_NAME_LENGTH} characters).`;
      }
      return null;
    },
    [normalizedExisting]
  );

  const onChange = (val: string) => {
    setWorkspaceName(val);
    setError(validate(val));
    // Track that user has manually edited the name (not during initial setup)
    if (!isInitialSetupRef.current) {
      userHasTypedRef.current = true;
    }
    // Track custom naming when user manually changes from auto-generated name (once)
    if (
      !customNameTracked &&
      autoGeneratedName &&
      val !== autoGeneratedName &&
      val.trim() &&
      normalizeWorkspaceName(val) !== normalizeWorkspaceName(autoGeneratedName)
    ) {
      setCustomNameTracked(true);
      void (async () => {
        const { captureTelemetry } = await import('../lib/telemetryClient');
        captureTelemetry('workspace_custom_named', { custom_name: 'true' });
      })();
    }
  };

  useEffect(() => {
    if (!isOpen) return;

    // Reset all form state on open
    setWorkspaceName('');
    setAutoGeneratedName('');
    setError(null);
    setTouched(false);
    setCustomNameTracked(false);
    setInitialPrompt('');
    setSelectedLinearIssue(null);
    setSelectedGithubIssue(null);
    setSelectedJiraIssue(null);
    setAutoApprove(false);
    setShowAdvanced(false);
    setLinearSetupOpen(false);
    setLinearApiKey('');
    setLinearConnectionError(null);
    setAutoOpenLinearSelector(false);
    setJiraSetupOpen(false);
    setJiraSite('');
    setJiraEmail('');
    setJiraToken('');
    setJiraConnectionError(null);
    userHasTypedRef.current = false;
    isInitialSetupRef.current = true;

    // Generate auto-generated name synchronously to avoid race condition
    // Default assumption: autoGenerateName is true (matches DEFAULT_SETTINGS)
    const suggested = generateFriendlyWorkspaceName(normalizedExisting);
    setAutoGeneratedName(suggested);
    setWorkspaceName(suggested);
    setError(validate(suggested));

    // Mark initial setup as complete after state updates
    // Use setTimeout to ensure this runs after React's state update cycle
    setTimeout(() => {
      isInitialSetupRef.current = false;
    }, 0);

    let cancel = false;
    window.electronAPI.getSettings().then((res) => {
      if (cancel) return;
      const settings = res?.success ? res.settings : undefined;

      // Provider
      const settingsProvider = settings?.defaultProvider;
      const defaultProvider: Provider = isValidProviderId(settingsProvider)
        ? (settingsProvider as Provider)
        : DEFAULT_PROVIDER;
      setDefaultProviderFromSettings(defaultProvider);
      setProviderRuns([{ provider: defaultProvider, runs: 1 }]);

      // Auto-approve default
      const autoApproveByDefault = settings?.tasks?.autoApproveByDefault ?? false;
      setAutoApprove(autoApproveByDefault && !!providerMeta[defaultProvider]?.autoApproveFlag);

      // Auto-generate task name
      // Only update if user hasn't typed yet
      const autoGenerate = settings?.tasks?.autoGenerateName ?? true;
      if (!userHasTypedRef.current) {
        if (!autoGenerate) {
          // User disabled auto-generate, clear the name
          setAutoGeneratedName('');
          setWorkspaceName('');
          setError(null);
        } else {
          // Ensure auto-generated name is set (may have been cleared by user typing)
          setWorkspaceName(suggested);
          setError(validate(suggested));
        }
      }
    });
    return () => {
      cancel = true;
    };
  }, [isOpen, normalizedExisting, validate]);

  // Check Linear connection when modal opens
  useEffect(() => {
    if (!isOpen) return;
    let cancel = false;
    const api: any = (window as any).electronAPI;
    if (!api?.linearCheckConnection) {
      setIsLinearConnected(false);
      return;
    }
    api
      .linearCheckConnection()
      .then((res: any) => {
        if (!cancel) setIsLinearConnected(!!res?.connected);
      })
      .catch(() => {
        if (!cancel) setIsLinearConnected(false);
      });
    return () => {
      cancel = true;
    };
  }, [isOpen]);

  // Check Jira connection when modal opens
  useEffect(() => {
    if (!isOpen) return;
    let cancel = false;
    const api: any = (window as any).electronAPI;
    api
      ?.jiraCheckConnection?.()
      .then((res: any) => {
        if (!cancel) setIsJiraConnected(!!res?.connected);
      })
      .catch(() => {
        if (!cancel) setIsJiraConnected(false);
      });
    return () => {
      cancel = true;
    };
  }, [isOpen]);

  const handleLinearConnect = useCallback(async () => {
    const trimmedKey = linearApiKey.trim();
    if (!trimmedKey || !window?.electronAPI?.linearSaveToken) {
      return;
    }

    setLinearConnectionError(null);
    try {
      const result = await window.electronAPI.linearSaveToken(trimmedKey);
      if (result?.success) {
        setIsLinearConnected(true);
        setLinearSetupOpen(false);
        setLinearApiKey('');
        setLinearConnectionError(null);
        setAutoOpenLinearSelector(true);
      } else {
        setLinearConnectionError(result?.error || 'Could not connect Linear. Try again.');
      }
    } catch (error) {
      console.error('Linear connect failed:', error);
      setLinearConnectionError('Could not connect Linear. Try again.');
    }
  }, [linearApiKey]);

  const handleGithubConnect = useCallback(async () => {
    if (!githubInstalled) {
      try {
        await window.electronAPI.openExternal('https://cli.github.com/manual/installation');
      } catch (error) {
        console.error('Failed to open GitHub CLI install docs:', error);
      }
      return;
    }
    try {
      const result = await githubLogin();
      if (result?.success) {
        // Connection status will update via useGithubAuth hook
      }
    } catch (error) {
      console.error('GitHub connect failed:', error);
    }
  }, [githubInstalled, githubLogin]);

  const handleJiraConnect = useCallback(async () => {
    try {
      setJiraConnectionError(null);
      const api: any = (window as any).electronAPI;
      const res = await api?.jiraSaveCredentials?.({
        siteUrl: jiraSite.trim(),
        email: jiraEmail.trim(),
        token: jiraToken.trim(),
      });
      if (res?.success) {
        setIsJiraConnected(true);
        setJiraSite('');
        setJiraEmail('');
        setJiraToken('');
        setJiraSetupOpen(false);
        setJiraConnectionError(null);
      } else {
        setJiraConnectionError(res?.error || 'Failed to connect.');
      }
    } catch (e: any) {
      setJiraConnectionError(e?.message || 'Failed to connect.');
    }
  }, [jiraSite, jiraEmail, jiraToken]);

  useEffect(() => {
    if (!hasAutoApproveSupport && autoApprove) {
      setAutoApprove(false);
    }
  }, [hasAutoApproveSupport, autoApprove]);

  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <motion.div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm"
          initial={shouldReduceMotion ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={shouldReduceMotion ? { opacity: 1 } : { opacity: 0 }}
          transition={shouldReduceMotion ? { duration: 0 } : { duration: 0.1, ease: 'easeOut' }}
          onClick={onClose}
        >
          <motion.div
            onClick={(e) => e.stopPropagation()}
            initial={shouldReduceMotion ? false : { opacity: 0, y: 8, scale: 0.995 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={
              shouldReduceMotion
                ? { opacity: 1, y: 0, scale: 1 }
                : { opacity: 0, y: 6, scale: 0.995 }
            }
            transition={
              shouldReduceMotion ? { duration: 0 } : { duration: 0.2, ease: [0.22, 1, 0.36, 1] }
            }
            className="mx-4 w-full max-w-md transform-gpu will-change-transform"
          >
            <Card className="relative max-h-[calc(100vh-48px)] w-full overflow-y-auto">
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="absolute right-2 top-2 z-10 h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
              <CardHeader className="space-y-1 pb-2 pr-12">
                <CardTitle className="text-lg">New Task</CardTitle>
                <CardDescription className="text-xs text-muted-foreground">
                  {projectName} • from origin/{defaultBranch}
                </CardDescription>
              </CardHeader>

              <CardContent>
                <Separator className="mb-2" />
                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    setTouched(true);
                    const err = validate(workspaceName);
                    if (err) {
                      setError(err);
                      return;
                    }
                    setIsCreating(true);
                    (async () => {
                      try {
                        const trimmedPrompt = initialPrompt.trim();
                        await onCreateWorkspace(
                          normalizeWorkspaceName(workspaceName),
                          hasInitialPromptSupport && trimmedPrompt ? trimmedPrompt : undefined,
                          providerRuns,
                          selectedLinearIssue,
                          selectedGithubIssue,
                          selectedJiraIssue,
                          hasAutoApproveSupport ? autoApprove : false
                        );
                        onClose();
                      } catch (error) {
                        console.error('Failed to create workspace:', error);
                      } finally {
                        setIsCreating(false);
                      }
                    })();
                  }}
                  className="space-y-4"
                >
                  <div>
                    <Label htmlFor="workspace-name" className="mb-2 block">
                      Task name
                    </Label>
                    <Input
                      id="workspace-name"
                      value={workspaceName}
                      onChange={(e) => onChange(e.target.value)}
                      onBlur={() => setTouched(true)}
                      placeholder="refactor-api-routes"
                      className={`w-full ${touched && error ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive' : ''}`}
                      aria-invalid={touched && !!error}
                      aria-describedby="workspace-name-error"
                      autoFocus
                    />
                  </div>

                  {workspaceName && (
                    <div className="flex items-center space-x-2 rounded-lg bg-gray-100 p-3 dark:bg-gray-700">
                      <GitBranch className="h-4 w-4 flex-shrink-0 text-gray-500" />
                      <span className="overflow-hidden break-all text-sm text-gray-600 dark:text-gray-400">
                        {normalizeWorkspaceName(workspaceName)}
                      </span>
                    </div>
                  )}

                  {/* Provider selector */}
                  <div className="flex items-center gap-4">
                    <Label className="shrink-0">AI Provider</Label>
                    <MultiProviderDropdown
                      providerRuns={providerRuns}
                      onChange={setProviderRuns}
                      defaultProvider={defaultProviderFromSettings}
                    />
                  </div>

                  <Accordion
                    type="single"
                    collapsible
                    value={showAdvanced ? 'advanced' : undefined}
                    className="space-y-2"
                  >
                    <AccordionItem value="advanced" className="border-none">
                      <AccordionTrigger
                        className="flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border-none bg-gray-100 px-3 text-sm font-medium text-foreground hover:bg-gray-200 hover:no-underline dark:bg-gray-700 dark:hover:bg-gray-600 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:shrink-0"
                        onPointerDown={(e) => {
                          // Toggle immediately on pointer down to avoid a required second click
                          // when another element inside had focus.
                          e.preventDefault();
                          const wasClosed = !showAdvanced;
                          setShowAdvanced((prev) => !prev);
                          if (wasClosed) {
                            void (async () => {
                              const { captureTelemetry } = await import('../lib/telemetryClient');
                              captureTelemetry('workspace_advanced_options_opened');
                            })();
                          }
                        }}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' || e.key === ' ') {
                            e.preventDefault();
                            const wasClosed = !showAdvanced;
                            setShowAdvanced((prev) => !prev);
                            if (wasClosed) {
                              void (async () => {
                                const { captureTelemetry } = await import('../lib/telemetryClient');
                                captureTelemetry('workspace_advanced_options_opened');
                              })();
                            }
                          }
                        }}
                      >
                        <span className="inline-flex items-center gap-2">
                          <Settings className="h-4 w-4 text-muted-foreground" />
                          <span>Advanced options</span>
                        </span>
                      </AccordionTrigger>
                      <AccordionContent className="space-y-4 px-0 pt-2" id="workspace-advanced">
                        <div className="flex flex-col gap-4 p-2">
                          {hasAutoApproveSupport ? (
                            <div className="flex items-center gap-4">
                              <Label className="w-32 shrink-0">Auto-approve</Label>
                              <div className="min-w-0 flex-1">
                                <label className="inline-flex cursor-pointer items-start gap-2 text-sm leading-tight">
                                  <input
                                    type="checkbox"
                                    checked={autoApprove}
                                    onChange={(e) => setAutoApprove(e.target.checked)}
                                    className="mt-[1px] h-4 w-4 shrink-0"
                                  />
                                  <div className="space-y-1">
                                    <span className="text-muted-foreground">
                                      Skip permissions for file operations
                                    </span>
                                    <a
                                      href="https://simonwillison.net/2025/Oct/22/living-dangerously-with-claude/"
                                      target="_blank"
                                      rel="noreferrer noopener"
                                      className="ml-1 inline-flex items-center gap-1 text-foreground underline"
                                    >
                                      Explanation
                                      <ExternalLink className="h-3 w-3" aria-hidden="true" />
                                    </a>
                                  </div>
                                </label>
                              </div>
                            </div>
                          ) : null}
                          <div className="flex items-start gap-4">
                            <Label htmlFor="linear-issue" className="w-32 shrink-0 pt-2">
                              Linear issue
                            </Label>
                            <div className="flex min-w-0 flex-1 items-center gap-2">
                              <LinearIssueSelector
                                selectedIssue={selectedLinearIssue}
                                onIssueChange={(issue) => {
                                  setSelectedLinearIssue(issue);
                                  if (issue) {
                                    setSelectedGithubIssue(null);
                                    setSelectedJiraIssue(null);
                                  }
                                }}
                                isOpen={isOpen}
                                disabled={
                                  !hasInitialPromptSupport ||
                                  !isLinearConnected ||
                                  !!selectedGithubIssue ||
                                  !!selectedJiraIssue
                                }
                                className="w-full"
                                autoOpen={autoOpenLinearSelector}
                                onAutoOpenHandled={() => setAutoOpenLinearSelector(false)}
                                placeholder={
                                  isLinearConnected ? 'Select a Linear issue' : 'Select issue'
                                }
                              />
                              {!isLinearConnected && (
                                <Button
                                  type="button"
                                  size="sm"
                                  variant="outline"
                                  className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                  onClick={() => setLinearSetupOpen(true)}
                                >
                                  Connect
                                </Button>
                              )}
                            </div>
                            <AnimatePresence>
                              {linearSetupOpen ? (
                                <motion.div
                                  className="fixed inset-0 z-[130] flex items-center justify-center px-3"
                                  initial={{ opacity: 0 }}
                                  animate={{ opacity: 1 }}
                                  exit={{ opacity: 0 }}
                                  onClick={() => setLinearSetupOpen(false)}
                                >
                                  <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                                  <motion.div
                                    className="relative z-10 w-full max-w-md rounded-xl border border-border/70 bg-background/95 p-4 shadow-2xl backdrop-blur-sm"
                                    initial={{ opacity: 0, scale: 0.95 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 0.95 }}
                                    transition={{ duration: shouldReduceMotion ? 0 : 0.15 }}
                                    onClick={(event) => event.stopPropagation()}
                                  >
                                    <LinearSetupForm
                                      apiKey={linearApiKey}
                                      onChange={(value) => setLinearApiKey(value)}
                                      onSubmit={() => void handleLinearConnect()}
                                      onClose={() => setLinearSetupOpen(false)}
                                      canSubmit={!!linearApiKey.trim()}
                                      error={linearConnectionError}
                                    />
                                  </motion.div>
                                </motion.div>
                              ) : null}
                            </AnimatePresence>
                          </div>
                          <div className="flex items-start gap-4">
                            <Label htmlFor="github-issue" className="w-32 shrink-0 pt-2">
                              GitHub issue
                            </Label>
                            <div className="flex min-w-0 flex-1 items-center gap-2">
                              <GitHubIssueSelector
                                projectPath={projectPath || ''}
                                selectedIssue={selectedGithubIssue}
                                onIssueChange={(issue) => {
                                  setSelectedGithubIssue(issue);
                                  if (issue) {
                                    setSelectedLinearIssue(null);
                                    setSelectedJiraIssue(null);
                                  }
                                }}
                                isOpen={isOpen}
                                disabled={
                                  !hasInitialPromptSupport ||
                                  !isGithubConnected ||
                                  !!selectedJiraIssue ||
                                  !!selectedLinearIssue
                                }
                                className="w-full"
                                placeholder={
                                  isGithubConnected ? 'Select a GitHub issue' : 'Select issue'
                                }
                              />
                              {!isGithubConnected && (
                                <Button
                                  type="button"
                                  size="sm"
                                  variant="outline"
                                  className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                  onClick={() => void handleGithubConnect()}
                                  disabled={githubLoading}
                                >
                                  {githubLoading ? (
                                    <>
                                      <Spinner size="sm" className="mr-1" />
                                      Connecting...
                                    </>
                                  ) : !githubInstalled ? (
                                    'Install CLI'
                                  ) : (
                                    'Connect'
                                  )}
                                </Button>
                              )}
                            </div>
                          </div>
                          <div className="flex items-start gap-4">
                            <Label htmlFor="jira-issue" className="w-32 shrink-0 pt-2">
                              Jira issue
                            </Label>
                            <div className="flex min-w-0 flex-1 items-center gap-2">
                              <JiraIssueSelector
                                selectedIssue={selectedJiraIssue}
                                onIssueChange={(issue) => {
                                  setSelectedJiraIssue(issue);
                                  if (issue) {
                                    setSelectedLinearIssue(null);
                                    setSelectedGithubIssue(null);
                                  }
                                }}
                                isOpen={isOpen}
                                disabled={
                                  !hasInitialPromptSupport ||
                                  !isJiraConnected ||
                                  !!selectedLinearIssue ||
                                  !!selectedGithubIssue
                                }
                                className="w-full"
                                placeholder={
                                  isJiraConnected ? 'Select a Jira issue' : 'Select issue'
                                }
                              />
                              {!isJiraConnected && (
                                <Button
                                  type="button"
                                  size="sm"
                                  variant="outline"
                                  className="h-9 shrink-0 whitespace-nowrap border-border/50 bg-transparent text-muted-foreground hover:border-border hover:bg-muted/50 hover:text-foreground"
                                  onClick={() => setJiraSetupOpen(true)}
                                >
                                  Connect
                                </Button>
                              )}
                            </div>
                            <AnimatePresence>
                              {jiraSetupOpen ? (
                                <motion.div
                                  className="fixed inset-0 z-[130] flex items-center justify-center px-3"
                                  initial={{ opacity: 0 }}
                                  animate={{ opacity: 1 }}
                                  exit={{ opacity: 0 }}
                                  onClick={() => setJiraSetupOpen(false)}
                                >
                                  <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                                  <motion.div
                                    className="relative z-10 w-full max-w-md rounded-xl border border-border/70 bg-background/95 p-4 shadow-2xl backdrop-blur-sm"
                                    initial={{ opacity: 0, scale: 0.95 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 0.95 }}
                                    transition={{ duration: shouldReduceMotion ? 0 : 0.15 }}
                                    onClick={(event) => event.stopPropagation()}
                                  >
                                    <JiraSetupForm
                                      site={jiraSite}
                                      email={jiraEmail}
                                      token={jiraToken}
                                      onChange={(u) => {
                                        if (typeof u.site === 'string') setJiraSite(u.site);
                                        if (typeof u.email === 'string') setJiraEmail(u.email);
                                        if (typeof u.token === 'string') setJiraToken(u.token);
                                      }}
                                      onClose={() => setJiraSetupOpen(false)}
                                      canSubmit={
                                        !!(jiraSite.trim() && jiraEmail.trim() && jiraToken.trim())
                                      }
                                      error={jiraConnectionError}
                                      onSubmit={() => void handleJiraConnect()}
                                    />
                                  </motion.div>
                                </motion.div>
                              ) : null}
                            </AnimatePresence>
                          </div>
                        </div>
                        <div className="flex items-start gap-4 p-2">
                          <Label htmlFor="initial-prompt" className="w-32 shrink-0">
                            Initial prompt
                          </Label>
                          <div className="min-w-0 flex-1">
                            <textarea
                              id="initial-prompt"
                              value={initialPrompt}
                              onChange={(e) => setInitialPrompt(e.target.value)}
                              disabled={!hasInitialPromptSupport}
                              placeholder={
                                !hasInitialPromptSupport
                                  ? 'Selected provider does not support initial prompts'
                                  : selectedLinearIssue
                                    ? `e.g. Fix the attached Linear ticket ${selectedLinearIssue.identifier} — describe any constraints.`
                                    : selectedGithubIssue
                                      ? `e.g. Fix the attached GitHub issue #${selectedGithubIssue.number} — describe any constraints.`
                                      : selectedJiraIssue
                                        ? `e.g. Fix the attached Jira ticket ${selectedJiraIssue.key} — describe any constraints.`
                                        : `e.g. Summarize the key problems and propose a plan.`
                              }
                              className={`min-h-[80px] w-full resize-none rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none ${!hasInitialPromptSupport ? 'opacity-50' : ''}`}
                              rows={3}
                            />
                          </div>
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  </Accordion>

                  <div className="flex justify-end">
                    <Button type="submit" disabled={!!validate(workspaceName) || isCreating}>
                      {isCreating ? (
                        <>
                          <Spinner size="sm" className="mr-2" />
                          Creating...
                        </>
                      ) : (
                        'Create'
                      )}
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );
};

export default WorkspaceModal;
